---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: konmari-cronjob
  namespace: kube-system
spec:
  schedule: "0 0 1 * ? *"
  concurrencyPolicy: "Forbid"
  jobTemplate:
    spec:
      template:
        metadata:
          name: konmari-pod
        spec:
          containers:
          - name: konmari
            image: rossy4613/konmari:v0.1.0
            volumeMounts:
            - mountPath: /policy-dir
              name: policy-volume
            command:
              - "/bin/konmari"
          restartPolicy: "Never"
          serviceAccountName: konmari-sa
