---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: konmari-cluster-role
  namespace: kube-system
rules: []
  - apiGroups: [""]
    resources: ["secrets", "configmaps"]
    verbs: ["get", "watch", "list", "delete"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: konmari-sa
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: konmari-cluster-role-binding
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: konmari-cluster-role
subjects:
  - name: konmari-sa
    kind: ServiceAccount
    namespace: kube-system
